### PR TITLE
Remove precomputed table of roots (#68)

### PR DESCRIPTION
**Pull request by henrycg**
There is no need to ship the large precomputed table of roots of unity;
it's possible to compute the table on the fly in linear time (in the
table size). This commit:
* removes the table from `prio/params.h`,
* removes the script that generates it (`scripts/gen_params.py`), and
* adds code to generate the table in `prio/config.c`.

### CODE REVIEW

**Comment by rhelmer** [comment]
@henrycg I am able to reproduce locally the test failure that we saw on macOS via Travis, by running `ptest -v` in a loop:

```
build/ptest/encrypt_test.c:306: mu_check((rv = (PrivateKey_decrypt(pvtkey_imp, decrypt, &plainLen, sizeof(decrypt), output, outputLen))) == SECSuccess) failed, resuming test case
build/ptest/encrypt_test.c:313: mu_check(rv == SECSuccess) failed, resuming test ca

Tests done:
	10 test suite(s) passed, 1 failed, 0 skipped.
	73 test case(s) passed, 1 failed.
	1441815 check(s) passed, 2 failed.
```

Looks like it's intermittent, took me ~10 tries locally to get that and I've seen it twice now.

I'm running the same test now for the previous revision just to make sure this is new.

**Comment by rhelmer** [comment]
> @henrycg I am able to reproduce locally the test failure that we saw on macOS via Travis, by running `ptest -v` in a loop:
> 
> ```
> build/ptest/encrypt_test.c:306: mu_check((rv = (PrivateKey_decrypt(pvtkey_imp, decrypt, &plainLen, sizeof(decrypt), output, outputLen))) == SECSuccess) failed, resuming test case
> build/ptest/encrypt_test.c:313: mu_check(rv == SECSuccess) failed, resuming test ca
> 
> Tests done:
> 	10 test suite(s) passed, 1 failed, 0 skipped.
> 	73 test case(s) passed, 1 failed.
> 	1441815 check(s) passed, 2 failed.
> ```
> 
> Looks like it's intermittent, took me ~10 tries locally to get that and I've seen it twice now.
> 
> I'm running the same test now for the previous revision just to make sure this is new.

Welp, I see it for the current master revision too (a898b5505d8b60ba7ef39127d7f9a2884f39f33d) so I have opened issue #71 so it doesn't need to block this PR.

**Comment by henrycg** [comment]
@rhelmer Since it looks like the intermittent failure here derives from #71, would you be willing to review this PR independent of the #71 bug fix. This weekend, I'll try to allocate some time to work on that as well.

**Comment by rhelmer** [comment]
> @rhelmer Since it looks like the intermittent failure here derives from #71, would you be willing to review this PR independent of the #71 bug fix. This weekend, I'll try to allocate some time to work on that as well.

Definitely, I don't think there's any reason to block this on #71.

**Comment by rhelmer** [comment]
Changes lgtm from a once-over, Firefox gtest passes and I am running it through the full CI too: https://treeherder.mozilla.org/#/jobs?repo=try&revision=00912d4f9fedf1c1fac7f70ad768c8b1dd1727ef

I'll look a bit more in-depth while that's running.

**Pull request merged**
