### PR TITLE
make roots data read-only, shareable between processes, and smaller on 64-bit platforms

### PR DESCRIPTION
**Pull request by froydnj**
This change shrinks the roots tables themselves by 32K on 64-bit platforms (sadly, no change on 32-bit platforms), places the tables into read-only memory so they can be shared between processes, and eliminates the run-time relocations previously required (tens of kilobytes on 64-bit platforms).

I confess to not building the whole thing, but I did at least verify that `params.h` builds as expected.

### CODE REVIEW

**Comment by froydnj** [comment]
Apparently `clang-format` was unhappy about the newly-modified file, so I've turned off the formatting requirement for the arrays.

**Comment by henrycg** [comment]
Thanks for working on this! If I understand correctly, the `RootsIndices` and `RootsInvIndices` arrays are just pointers into the `Roots` string. Since the numbers in the roots string are all integers mod an 87-bit prime, we can pad these integers all up to be exactly 22 bytes in length. Then we don't need to store `RootsIndices` and `RootsInvIndices` at all -- we can just compute index of the `i`th root as something like `22*i + 2`. Does that sound right to you?

Also, just out of curiosity: why is there no savings on 32-bit platforms?

**Comment by henrycg** [comment]
> > Then we don't need to store `RootsIndices` and `RootsInvIndices` at all -- we can just compute index of the `i`th root as something like `23*i + 2`. Does that sound right to you?
> 
> This approach would work too! I am all for eliminating even more space. :)

Great. Would you be willing to update the PR to get rid of `RootsIndices` and `RootsInvIndices` and just compute the indices directly? If so, I'll be able to review it quickly. Otherwise, it might take me some time to write up the patch myself.

**Comment by froydnj** [comment]
Yes, I'll have time to write that up tomorrow morning.

**Comment by henrycg** [comment]
I just noticed that you updated the PR (for some reason I didn't get an email). Sorry for the delay in reviewing this... I'll do that now.

**Pull request merged**
