### PR TITLE
issue #25 - use clang as the compiler

### PR DESCRIPTION
**Pull request by rhelmer**
I'd suggest using Clang as the supported compiler - I know the big open source projects are moving to it on all platforms, and there are a lot of supported static analysis tools.

### CODE REVIEW

**Comment by rhelmer** [comment]
(this is how we compile libprio for Firefox too FWIW)

**Comment by rhelmer** [comment]
Hm, ok might have to come back to this later... wfm locally, could be a SCons 2.0 vs 3.0 thing.

**Comment by rhelmer** [comment]
Welp instead of randomly shooting in the dark, going to install Travis' docker image locally, they are doing something weird in their environment: https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image

**Comment by rhelmer** [comment]
@henrycg had to learn a *lot* more about Travis than I thought I ever wanted to :) But, figured out a relatively clean way to upgrade SCons and enable Clang as the default compiler.

**Comment by henrycg** [comment]
This works for me on Linux with v3.0.1 but fails on Mac with scons v2.3.2 with the error:
```
EnvironmentError: No tool named 'clang': not a Zip file:
```
Is that expected? If so, maybe we can add a comment in the `README` that specifies that we require scons version 3+.

**Comment by rhelmer** [comment]
@henrycg yeah this is a SCons 2 vs. 3 thing, which is why I had to jump through the hoops to upgrade it as part of this PR (the Trusty packages are so old!)

I'll update README

**Pull request merged**
