### PR TITLE
Fix issue #17 - do not use VLAs as MSVC only supports C90

### PR DESCRIPTION
**Pull request by henrycg**
I couldn't figure out how to update your pull request, so I am opening a new one here.

### CODE REVIEW

**Comment by rhelmer** [comment]
Hm, so this does get the build further, now it's hitting:

`z:/build/build/src/third_party/prio/prio/prg.c(53): error C2059: syntax error: '}'`

https://treeherder.mozilla.org/#/jobs?repo=try&revision=f5a0ea9a8e6e7ab0656bc2b9f92a0faf19781d63&selectedJob=195995627

**Comment by henrycg** [comment]
How important is it that libprio support MSVC? With a few more tries, we can probably get libprio to compile with MSVC, but as we modify and extend the library, it will probably break again and will be a bit annoying to debug.

Getting rid of the variable-length arrays is easy enough (with the `-Wvla` flag), but if there are more useful C99 features that MSVC doesn't support, I am sure whether it's worth the trouble to try to eliminate our usage of them. I would be happy to just use C90 (with `-std=c90`) but since `msgpack-c` doesn't compile with C90, we can't do that either.

If it's important though, we can definitely make it work.

**Comment by rhelmer** [comment]
Not important for Firefox! We are almost certainly not going to ship MSVC (https://github.com/mozilla/libprio/issues/17#issuecomment-415832217)

I think it'd be cool for libprio's sake but no rush, I am working on disable libprio on that platform in https://bugzilla.mozilla.org/show_bug.cgi?id=1485946 (there is a weird complication that has nothing to do with libprio, but I expect that to be resolved soon)

Sorry for the confusion on priority!

**Comment by henrycg** [comment]
Great. Thanks for letting me know. I'll leave this for later then.

**Comment by henrycg** [comment]
That sounds like a good plan. There is a C89 msgpack implementation, but it looks more difficult to use and is not very well documented: https://github.com/libmpack/libmpack 

I'll close this PR for now. If down the line we want to support MSVC, we can revisit this.

**Pull request closed without merging**
