### PR TITLE
Cleanup .travis.yml

### PR DESCRIPTION
**Pull request by jbeich**
- msgpack is now a regular package
- SConstruct already adds macOS flags

### CODE REVIEW

**Comment by henrycg** [comment]
Let me know when this is ready and I'll take a look at the changes.

**Comment by jbeich** [comment]
*Sigh* macOS fails because of `brew install` but previously exit code was ignored.

**Comment by jbeich** [comment]
All green. Please, review.

**Comment by henrycg** [comment]
Awesome. Looks great!

**Pull request merged**
