### PR TITLE
b-bit integer circuit

### PR DESCRIPTION
**Pull request by degregat**
This is an implementation of the b-bit integer circuit as described in the prio paper.

It is explained in encode.h, circuit.h and prg.h.

If you notice any missing tests or my explanations in the comments prove to be insufficient, please let me know so I can fix that.

EIntArray interface handlers felt more natural to do this way but I could remodel them after mparray.h:
https://github.com/degregat/libprio/blob/c1295db54c6c45a9cb7da2688041391467c17ae2/prio/encode.c#L88

Some questions from my side so far: 
- Up to which b do we want to support. The maximum depends on how many submissions we want to fit into an usigned long long which also depends on the platform:
https://github.com/degregat/libprio/blob/a71fe8c26906aaa0f072086bdef8cb7b5ce7e96e/prio/config.c#L56

- Two regarding the use of msgpack, which was unclear to me from the msgpack-c documentation: Do we gain anything from using the msgpack arrays in the two places below:
https://github.com/degregat/libprio/blob/a71fe8c26906aaa0f072086bdef8cb7b5ce7e96e/prio/serial.c#L193
https://github.com/degregat/libprio/blob/a71fe8c26906aaa0f072086bdef8cb7b5ce7e96e/prio/serial.c#L210

- I am unsure about the parameters for the new EInt tests in prg_test:
https://github.com/degregat/libprio/blob/a71fe8c26906aaa0f072086bdef8cb7b5ce7e96e/ptest/prg_test.c#L419

- Should the maximum value be computed in PrioConfig? Apart from the following it only gets used in tests: https://github.com/degregat/libprio/blob/a71fe8c26906aaa0f072086bdef8cb7b5ce7e96e/prio/encode.c#L51

- Should tmp be allocated inside the accumulator or not:
https://github.com/degregat/libprio/blob/c1295db54c6c45a9cb7da2688041391467c17ae2/prio/prg.c#L123

I know this PR contains sizeable changes, so I am open to all feedback, discussion and reworking parts of this.

### CODE REVIEW

**Comment by henrycg** [comment]
Thanks for the work on this! Having support for integer statistics would be great, so I'm excited to see this merged into libprio.

Since this is a big PR, it might make sense for us to discuss a bit offline about how best to proceed. For me, two major design goals are:

1. maintain backwards compatibility with the current API and
2. modify the core cryptographic routines as little as possible.

The first goal should be easy to achieve with a relatively minor tweak to the PR.

It might take a bit more work to achieve the second goal, but I think it's still possible (and also probably worth the trouble). In particular, it should be possible to implement support for b-bit integers by having the client invoke the existing `PrioClient_encode` routine in a black-box way. On the server side, the only change would need to be in the `PrioTotalShare_*` routines.

Implementing the change this way could potentially really reduce the size of the diff, which would make the PR easier to review and would reduce the chances of introducing a bug into the guts of the code, on which consumers of the library rely. Does that make sense? I'll follow up by email to see what next steps might make sense.

**Comment by degregat** [comment]
Yes, this makes sense. I did not assume that this version would be the final one to be merged, and I am happy to work towards the proposed goals.

**Comment by degregat** [comment]
#91 now supersedes this PR. We can close this when the other gets merged the latest.

**Comment by henrycg** [comment]
Closed in favor of #91

**Pull request closed without merging**
