### PR TITLE
Clang format 9.0

### PR DESCRIPTION
**Pull request by degregat**
It was reformatted with clang-format 9.0.0 issuing the following command in the project root:
```clang-format --style=Mozilla -i include/*.h pclient/*.c prio/*.c prio/*.h ptest/*.c ptest/*.h```

### CODE REVIEW

**Comment by degregat** [comment]
Left out mpi/ but ptest/mutest.* was included, was this correct? (See #79?)

**Comment by henrycg** [comment]
@rhelmer How do you want to handle this? I'm happy with whatever you decide.

**Comment by rhelmer** [comment]
> Left out mpi/ but ptest/mutest.* was included, was this correct (See #79)?
> 
> If merging now conflicts with #84, I can redo this after it is done and send another PR.

@degregat yeah let's please merge #84 before we land this. Thanks for doing this btw!

**Comment by degregat** [comment]
No problem. Should I continue my work then in 9.0 or 3.9? Will probably push a reworked PR for the ints tomorrow. I tried reformatting it with clang-format from the 3.9.0 release, but that also complained about parts of the code I never touched. I could just try my luck with the CI though in case thats a minor style difference and no breaking change.

**Comment by degregat** [comment]
Just installed 3.9.1 and will reformat.

**Comment by degregat** [comment]
I'll reformat when all the major current PRs are done.

**Pull request closed without merging**
