### PR TITLE
issue #43 - add travis-ci integration for osx

### PR DESCRIPTION
**Pull request by adeeburrahman**
added support for testing libprio on osx

### CODE REVIEW

**Comment by henrycg** [comment]
@rhelmer Would you be willing to review this one? It looks good to me, but I don't have much experience with travis-ci.

**Comment by adeeburrahman** [comment]
Homebrew doesn't appear to have version 3.9 available and only has the latest. However the linux testing should still be using version 3.9.

**Comment by rhelmer** [comment]
@adeeburrahman I don't think `clang-format-3.9` is available as a standalone package in Homebrew, but I can get it if I `brew install llvm@3.9`:

```
$ /usr/local/opt/llvm\@3.9/bin/clang-format -version
clang-format version 3.9.1 (tags/RELEASE_391/final)
```

Does that work for you? The only reason this matters is that we found subtle differences in the behavior of `clang-format` across different versions, if that is more directly fixable (or isn't happening anymore) I have no objection to lifting this though.

Thanks again, sorry for the hassle around this :) The rest of your change looks great.

**Comment by adeeburrahman** [comment]
I was just opposed to installing the llvm. For a couple of reasons:
- the large size
- using clang-format would involve either creating an alias to the file or   put that directory in the beginning of the path causing errors on compile

**Comment by adeeburrahman** [comment]
I can make do with either installing llvm@3.9 and creating a symbolic link or moving `clang-format.sh` to the linux only instructions. Do you have any preference?

**Comment by rhelmer** [comment]
@henrycg oh you're right, let's just skip the linting on macOS.

**Comment by rhelmer** [comment]
> I can make do with either installing llvm@3.9 and creating a symbolic link or moving `clang-format.sh` to the linux only instructions. Do you have any preference?

Making it Linux only seems like the right move, thanks!

**Comment by adeeburrahman** [comment]
@rhelmer Should be good to go now, sorry for the hassle.

**Comment by rhelmer** [comment]
@adeeburrahman No problem at all! Thanks again for your contribution.

**Pull request merged**
