### PR TITLE
Add auto-generated documentation

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This adds auto-generated documentation through doxygen.

Generated documentation can be previewed at https://acmiyaguchi.github.io/libprio. The [mprio.h](https://acmiyaguchi.github.io/libprio/mprio_8h.html) can be found here; it includes a source tree map and comments from the header itself. I'm planning on using a doxy2swig script to generate better documentation for the python bindings in #56.

The `.travis.yml` has been updated to auto-deploy documentation to a `gh-pages` branch. I've also fixed a few bugs that were preventing the build from completing by upgrading libnss.

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
I followed the instructions on this [gist](https://gist.github.com/vidavidorra/548ffbcdae99d752da02) to get the page setup. In particular, the section on [creating a clean `gh-pages` branch](https://gist.github.com/vidavidorra/548ffbcdae99d752da02#create-a-clean-gh-pages-branch) and [providing the proper credentials to TravisCI](https://gist.github.com/vidavidorra/548ffbcdae99d752da02#provide-travis-ci-with-encrypted-credentials-for-publishing-to-gh-pages) are needed to operationalize the auto-deployed docs.

@rhelmer or @henrycg r?

**Comment by henrycg** [comment]
Thanks for putting this together! It looks good to me, but I'll defer to @rhelmer for the review, since I'm not sure what standards Mozilla uses for documenting projects like this.

**Review by rhelmer — APPROVED** [review]

**Comment by rhelmer** [comment]
@acmiyaguchi could you make sure this is rebased correctly? I used github's merge tool.

**Comment by rhelmer** [comment]
> @rhelmer I rebased the new changes, this should be good to go. Make sure to refer to [#59 (comment)](https://github.com/mozilla/libprio/pull/59#issuecomment-446792449) if you want to deploy to mozilla.github.io

cool thanks @acmiyaguchi for the gist, I am working through that and will set it up so Travis publishes the docs.

**Comment by rhelmer** [comment]
> > @rhelmer I rebased the new changes, this should be good to go. Make sure to refer to [#59 (comment)](https://github.com/mozilla/libprio/pull/59#issuecomment-446792449) if you want to deploy to mozilla.github.io
> 
> cool thanks @acmiyaguchi for the gist, I am working through that and will set it up so Travis publishes the docs.

Sorry I have been dragging my feet on this, will resurrect my branch and move it forward soonish.

**Comment by henrycg** [comment]
@rhelmer @acmiyaguchi Do you know what the status of this PR is? If it's still in progress, I will leave it open.

**Comment by acmiyaguchi** [comment]
I can rebase to include new changes, but it still requires configuration within Travis so CI can push to a `gh-pages` branch.

**Comment by henrycg** [comment]
(Undid my bogus merge commit.)

@acmiyaguchi What specifically needs to happen with Travis CI? I'm happy to try to help so that we can merge this.

**Comment by henrycg** [comment]
It looks like this PR is pretty stale, so I will close it for now.

**Pull request closed without merging**
