### PR TITLE
move extern C above includes

### PR DESCRIPTION
**Pull request by rhelmer**
r? @henrycg

### CODE REVIEW

**Comment by henrycg** [comment]
This looks good to me.

**Comment by rhelmer** [comment]
Hm, so I tried to do a cross-platform tryserver run which included this patch, however it's still failing as before: https://treeherder.mozilla.org/logviewer.html#?job_id=192932388&repo=try&lineNumber=37301-37306

**Comment by rhelmer** [comment]
Oh, ugh, now it looks like *only* macOS is failing, I can repro this locally:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=015fef4b5e38d21dfc0bbcbab3c555adf3e82470

Undefined symbols for `_NSS_ShutdownContext` and `_NSS_InitContext`,

**Comment by rhelmer** [comment]
This both makes sense and WFM locally, thanks!

Going to push all platforms to try now to see if we got everything.

**Pull request merged**
