### PR TITLE
Fix popen() for Linux and add debugging info

### PR DESCRIPTION
**Pull request by henrycg**
* popen() on Linux takes only "r" as a mode
* Add some `printf`s for debugging

### CODE REVIEW

**Comment by rhelmer** [comment]
Here's what I see with the applied patch:

```
$ ./browser-test ~/src/mozilla-central/obj-x86_64-apple-darwin17.6.0/dist/bin/xpcshell 
== Prio browser test utility. ==
(Note: Expects to be run in the same directory as encode-once.js.)
Using srand seed 16807
> /Users/rhelmer/src/mozilla-central/obj-x86_64-apple-darwin17.6.0/dist/bin/xpcshell encode-once.js C83DDBE50B61676C7648CA2795A5CD01378DCFB2F02DD1EC7AC81F89603D3310 409D002746A575266D75385C7EB104D419CC757EB81E240C33F31F4431A1ED42 282475249 1 0 0
Ran command.
Reading...
Getting line of input.
Got line of input.
Reading string A
Read string A
Reading string B
Read string B
Read reply from browser. LenA: 229, LenB: 160
Imported data.
Set data.
Checking validity.
Are valid.
Warning: unexpected failure.
```

**Comment by henrycg** [comment]
What version of `encode-once.js ` are you using? In the version that was working for me, I had:
```
    'browserIsUserDefault': Number(param1),
    'safeModeUsage': Number(param2),
    'startupCrashDetected': Number(param3)
```
Note that I am converting the parameters to `Number`s instead of `Boolean`s, since I think in JS-land, all strings are "true".

**Comment by rhelmer** [comment]
This is the `encode-once.js` from https://github.com/mozilla/libprio/issues/7#issuecomment-412163994

Oh good catch on the Boolean thing, I was naively assuming the args were ints not strings :/

What should work is:

`(param1 == true)`

For example:

```
> ("0" == true)
false
> ("1" == true)
true
> ("2" == true)
false
```

**Comment by rhelmer** [comment]
Here's the full patch I'm using for clarity:

```
diff --git a/browser-test/encode-once.js b/browser-test/encode-once.js
index 1c4336b..978536d 100644
--- a/browser-test/encode-once.js
+++ b/browser-test/encode-once.js
@@ -7,21 +7,39 @@
  */
 
 ChromeUtils.import('resource://gre/modules/Services.jsm');
-Services.prefs.setStringPref('prio.publicKeyA', arguments[0]);
-Services.prefs.setStringPref('prio.publicKeyB', arguments[1]);
-
-var prio = new PrioEncoder();
-
-var l = prio.encode(arguments[2], {
-  'hasCrashedInLast24Hours': Number(arguments[3]),
-  'hasDefaultHomepage': Number(arguments[4]),
-  'hasUsedPrivateBrowsing': Number(arguments[5])
-}).then(function(v) {
-  function intToHex(x) { return x.toString(16).padStart(2, '0'); };
-  function toHexString(arr) { return arr.map(intToHex).join(','); };
-  console.log(toHexString(v[0]) + ',$' + toHexString(v[1]));
-  console.log('');
-}, function(v) {
-  console.log('Failure.');
-  console.log(v);
-});
+
+let [publicKeyA, publicKeyB, batchID, param1, param2, param3] = arguments;
+
+Services.prefs.setStringPref('prio.publicKeyA', publicKeyA);
+Services.prefs.setStringPref('prio.publicKeyB', publicKeyB);
+
+async function test() {
+  let params =  {
+    'browserIsUserDefault': Number(param1),
+    'safeModeUsage': Number(param2),
+    'startupCrashDetected': Number(param3)
+  };
+
+  try {
+    let result = await PrioEncoder.encode(batchID, params);
+
+    function toArr(bStr) {
+      var len = bStr.length;
+      var u8_array = new Uint8Array(len);
+      for (var i = 0; i < len; i++) {
+        u8_array[i] = bStr.charCodeAt(i);
+      }
+      return u8_array;
+    }
+    const toHexString = bytes =>
+      bytes.reduce((str, byte) => str + byte.toString(16).padStart(2, '0') + ',', '');
+
+    console.log(toHexString(toArr(result.a)) + '$' + toHexString(toArr(result.b)));
+    console.log('');
+  } catch(e) {
+    console.log('Failure.', e);
+    console.log(v);
+  }
+}
+
+test().then();
\ No newline at end of file
diff --git a/browser-test/main.c b/browser-test/main.c
index b272780..c121899 100644
--- a/browser-test/main.c
+++ b/browser-test/main.c
@@ -64,7 +64,9 @@ read_browser_reply (FILE *infile,
   char *raw_input = NULL;
   size_t rawLen = 0;
 
+  puts ("Getting line of input.");
   P_CHECKCB (getline (&raw_input, &rawLen, infile) > 0);
+  puts ("Got line of input.");
 
   P_CHECKA (*for_server_a = malloc (rawLen * sizeof (unsigned char)));
   P_CHECKA (*for_server_b = malloc (rawLen * sizeof (unsigned char)));
@@ -76,10 +78,14 @@ read_browser_reply (FILE *infile,
 
   // Header is 14 chars long
   const char *new_input;
+  puts ("Reading string A");
   P_CHECKC (read_string_from_hex (for_server_a, aLen, raw_input + 14, &new_input));
+  puts ("Read string A");
 
   // Skip over for_server_a string and one-char delimeter
+  puts ("Reading string B");
   P_CHECKC (read_string_from_hex (for_server_b, bLen, new_input, NULL));
+  puts ("Read string B");
 
 cleanup:
   if (raw_input) free (raw_input);
@@ -151,7 +157,8 @@ verify_full (const char *path_to_xpcshell, int pathlen)
       data_items[0], data_items[1], data_items[2]);
 
   printf ("> %s\n", cmd);
-  P_CHECKA (shell = popen(cmd, "r+"));
+  P_CHECKA (shell = popen(cmd, "r"));
+  puts("Ran command.");
 
   // Use the default configuration parameters.
   P_CHECKA (cfg = PrioConfig_new (ndata, pkA, pkB, batch_id_str, 
@@ -189,7 +196,9 @@ verify_full (const char *path_to_xpcshell, int pathlen)
   // Read in the client data packets
   unsigned int aLen = 0, bLen = 0;
 
+  puts ("Reading...");
   P_CHECKC (read_browser_reply (shell, &for_server_a, &aLen, &for_server_b, &bLen));
+  printf ("Read reply from browser. LenA: %u, LenB: %u\n", aLen, bLen);
 
   // II. VALIDATION PROTOCOL. (at servers)
   //
@@ -210,11 +219,13 @@ verify_full (const char *path_to_xpcshell, int pathlen)
   // Set up a Prio verifier object.
   P_CHECKC (PrioVerifier_set_data (vA, for_server_a, aLen));
   P_CHECKC (PrioVerifier_set_data (vB, for_server_b, bLen));
+  puts("Imported data.");
 
   // Both servers produce a packet1. Server A sends p1A to Server B
   // and vice versa.
   P_CHECKC (PrioPacketVerify1_set_data (p1A, vA));
   P_CHECKC (PrioPacketVerify1_set_data (p1B, vB));
+  puts("Set data.");
 
   // Both servers produce a packet2. Server A sends p2A to Server B
   // and vice versa.
@@ -225,8 +236,10 @@ verify_full (const char *path_to_xpcshell, int pathlen)
   // is valid. (In fact, only Server A needs to perform this 
   // check, since Server A can just tell Server B whether the check 
   // succeeded or failed.) 
+  puts ("Checking validity.");
   P_CHECKC (PrioVerifier_isValid (vA, p2A, p2B)); 
   P_CHECKC (PrioVerifier_isValid (vB, p2A, p2B)); 
+  puts ("Are valid.");
 
   // If we get here, the client packet is valid, so add it to the aggregate
   // statistic counter for both servers.
```

**Comment by rhelmer** [comment]
If this works for you on Linux I am not super concerned and would rather spend time converting this over to a cross-platform xpcshell test in mozilla-central... mostly I was looking for a sanity test since I'd like to land this soon in m-c.

**Comment by henrycg** [comment]
Yes, when I build the browser using `f284ac619dc7`, then apply this patch to libprio, the browser-test utility reports success.

**Comment by rhelmer** [comment]
OK great, that is my primary concern, I think we should not bother to debug further and just put our effort into a test in mozilla-central as you suggest :)

It makes more sense for libprio to have more generic non-app-specific tests and for tests that require a running Firefox to live in m-c, so folks will avoid breaking `PrioEncoder` accidentally etc.

**Pull request merged**
